<?php

namespace Application\GeoTeKosBundle\Repository;

/**
 * ColisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColisRepository extends \Doctrine\ORM\EntityRepository
{
}
